
# This is a basic workflow to help you get started with Actions

name: List Hardware and Push HTML page to GitHub Pages

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  list-hardware:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - run: sudo lshw -html > ./index.html
      - run: |
          git config user.email "wei.he@mlh.io"
          git config user.name "Wei"
          git commit -am "Add lshw html"
          git push origin HEAD:gh-pages
